## Stages by grouping
shared:
  image: node:14
  steps:
    - init: echo 'init'
jobs:
  triggering-stage:
    requires: [ ~pr, ~commit ]
  ci-deploy:
    requires: [ ~stage@integration:setup ]
  ci-test:
    requires: [ ci-deploy ]
    steps:
      - fail: exit 1;
  ci-certify:
    requires: [ ci-test ]
  triggered-by-stage:
    requires: [ ~stage@integration:teardown ]

stages:
  integration:
    requires: [triggering-stage]
    jobs: [ci-deploy, ci-test, ci-certify]
    description: "This stage will deploy the latest application to CI environment and certifies it after the tests are passed."
    setup:
      image: node:14
      steps:
        -   init: echo 'integration setup'
    teardown:
      image: node:14
      steps:
        -   init: echo 'integration teardown'