childPipelines:
  scmUrls:
    - git@github.com:sagar1312/screwdriver-config.git#main:external-config-child-1
    - git@github.com:sagar1312/screwdriver-config.git#main:external-config-child-3
jobs:
  main:
    image: node:8
    steps:
      - secrets: echo A:$A_SECRET && echo B:$B_SECRET && echo C:$C_SECRET
    requires: [~pr, ~commit]
    secrets:
      - A_SECRET
      - B_SECRET
      - C_SECRET