shared:
  image: node:21
  steps:
    - init: echo 'init'

annotations:
  screwdriver.cd/chainPR: true

jobs:
  ci-setup-virtual:
    requires: [ ~pr, ~commit ]
  ci-deploy-blue:
    requires: [ ~ci-setup-virtual ]
