shared:
  image: node:14
  steps:
    - init: echo 'init'
jobs:
  triggering-stage:
    requires: [~pr, ~commit]
  ci-deploy:
    requires: [ ~stage@integration:setup ]
  ci-test-functional:
    requires: [ ci-deploy ]
    steps:
      - set-meta: meta set functional-test-status 'PASSED'
  ci-test-integration:
    requires: [ ci-deploy ]
    steps:
      - sleep: sleep 30;
      - set-meta: meta set integration-test-status 'FAILED'
      - fail: exit 1;
  ci-certify:
    requires: [ ci-test-functional, ci-test-integration ]
  triggered-by-stage:
    requires: [ ~stage@integration:teardown ]

stages:
  integration:
    requires: [triggering-stage]
    jobs: [ci-deploy, ci-test-functional, ci-test-integration, ci-certify]
    description: "This stage will deploy the latest application to CI environment and certifies it after all the tests are passed."
    setup:
      image: node:14
      steps:
        -   init: echo 'integration setup'
        -   set-meta: meta set integration-setup 'PASSED'
    teardown:
      image: node:14
      steps:
        -   init: echo 'integration teardown'