shared:
    image: node:22
    steps:
        - init: echo 'init'
jobs:
    component:
        requires: [~pr, ~commit]
        description: "Component job"
    publish:
        requires: [ component ]
    triggers_downstream:
        requires: [ publish ]